# Not sure if this is strictly needed. Disabling legacy Touchpads
# This _should_ just be a duplicate exposure of hardware for what i assume
# are compatibility reasons.
# Check what's there with `xinput list`
Section "InputClass"
	Identifier "SynPS/2 Synaptics TouchPad"
	MatchProduct "SynPS/2 Synaptics TouchPad"
	MatchIsTouchpad "on"
	MatchOS "Linux"
	MatchDevicePath "/dev/input/event*"
	Option "Ignore" "on"
EndSection
